/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LadderRouteImport } from './routes/ladder'
import { Route as DiapRouteImport } from './routes/diap'
import { Route as IndexRouteImport } from './routes/index'

const LadderRoute = LadderRouteImport.update({
  id: '/ladder',
  path: '/ladder',
  getParentRoute: () => rootRouteImport,
} as any)
const DiapRoute = DiapRouteImport.update({
  id: '/diap',
  path: '/diap',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diap': typeof DiapRoute
  '/ladder': typeof LadderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diap': typeof DiapRoute
  '/ladder': typeof LadderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diap': typeof DiapRoute
  '/ladder': typeof LadderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diap' | '/ladder'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diap' | '/ladder'
  id: '__root__' | '/' | '/diap' | '/ladder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiapRoute: typeof DiapRoute
  LadderRoute: typeof LadderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ladder': {
      id: '/ladder'
      path: '/ladder'
      fullPath: '/ladder'
      preLoaderRoute: typeof LadderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diap': {
      id: '/diap'
      path: '/diap'
      fullPath: '/diap'
      preLoaderRoute: typeof DiapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiapRoute: DiapRoute,
  LadderRoute: LadderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
