/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhiteboardRouteImport } from './routes/whiteboard'
import { Route as OrgchartRouteImport } from './routes/orgchart'
import { Route as LadderRouteImport } from './routes/ladder'
import { Route as DiapRouteImport } from './routes/diap'
import { Route as IndexRouteImport } from './routes/index'

const WhiteboardRoute = WhiteboardRouteImport.update({
  id: '/whiteboard',
  path: '/whiteboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgchartRoute = OrgchartRouteImport.update({
  id: '/orgchart',
  path: '/orgchart',
  getParentRoute: () => rootRouteImport,
} as any)
const LadderRoute = LadderRouteImport.update({
  id: '/ladder',
  path: '/ladder',
  getParentRoute: () => rootRouteImport,
} as any)
const DiapRoute = DiapRouteImport.update({
  id: '/diap',
  path: '/diap',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diap': typeof DiapRoute
  '/ladder': typeof LadderRoute
  '/orgchart': typeof OrgchartRoute
  '/whiteboard': typeof WhiteboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diap': typeof DiapRoute
  '/ladder': typeof LadderRoute
  '/orgchart': typeof OrgchartRoute
  '/whiteboard': typeof WhiteboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diap': typeof DiapRoute
  '/ladder': typeof LadderRoute
  '/orgchart': typeof OrgchartRoute
  '/whiteboard': typeof WhiteboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diap' | '/ladder' | '/orgchart' | '/whiteboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diap' | '/ladder' | '/orgchart' | '/whiteboard'
  id: '__root__' | '/' | '/diap' | '/ladder' | '/orgchart' | '/whiteboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiapRoute: typeof DiapRoute
  LadderRoute: typeof LadderRoute
  OrgchartRoute: typeof OrgchartRoute
  WhiteboardRoute: typeof WhiteboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whiteboard': {
      id: '/whiteboard'
      path: '/whiteboard'
      fullPath: '/whiteboard'
      preLoaderRoute: typeof WhiteboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgchart': {
      id: '/orgchart'
      path: '/orgchart'
      fullPath: '/orgchart'
      preLoaderRoute: typeof OrgchartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ladder': {
      id: '/ladder'
      path: '/ladder'
      fullPath: '/ladder'
      preLoaderRoute: typeof LadderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diap': {
      id: '/diap'
      path: '/diap'
      fullPath: '/diap'
      preLoaderRoute: typeof DiapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiapRoute: DiapRoute,
  LadderRoute: LadderRoute,
  OrgchartRoute: OrgchartRoute,
  WhiteboardRoute: WhiteboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
